export interface AttendanceTokenPayload {
  batchId: string;
  subjectId: string;
  timestamp: number; // epoch ms
  expiry: number; // epoch ms
}

const TOKEN_SECRET = import.meta.env.VITE_TOKEN_SECRET || 'dev-secret';

/**
 * Generate a signed token (base64url) for attendance QR.
 * Uses SHA-256 HMAC via Web Crypto API.
 */
export async function generateSignedToken(payload: AttendanceTokenPayload): Promise<string> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(TOKEN_SECRET),
    { name: 'HMAC', hash: { name: 'SHA-256' } },
    false,
    ['sign', 'verify']
  );
  const payloadStr = JSON.stringify(payload);
  const signature = await crypto.subtle.sign('HMAC', key, encoder.encode(payloadStr));
  const sigBase64 = btoa(String.fromCharCode(...new Uint8Array(signature)));
  const token = `${btoa(payloadStr)}.${sigBase64}`;
  return token.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, ''); // url-safe
}

/**
 * Verify a token generated by generateSignedToken.
 * Returns payload if valid, otherwise null.
 */
export async function verifySignedToken(token: string): Promise<AttendanceTokenPayload | null> {
  try {
    const [payloadB64, sigB64] = token.split('.');
    if (!payloadB64 || !sigB64) return null;
    const payloadStr = atob(payloadB64.replace(/-/g, '+').replace(/_/g, '/'));
    const payload: AttendanceTokenPayload = JSON.parse(payloadStr);
    const encoder = new TextEncoder();
    const key = await crypto.subtle.importKey(
      'raw',
      encoder.encode(TOKEN_SECRET),
      { name: 'HMAC', hash: { name: 'SHA-256' } },
      false,
      ['verify']
    );
    const expectedSig = await crypto.subtle.sign('HMAC', key, encoder.encode(payloadStr));
    const expectedB64 = btoa(String.fromCharCode(...new Uint8Array(expectedSig)));
    const normExpected = expectedB64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    return normExpected === sigB64 ? payload : null;
  } catch {
    return null;
  }
}
